### ISSUE TITLE
Why not an AbstractUnitRange instance?

### ISSUE THREAD

**Issue by nsajko** [Tokazama/StaticRanges.jl#27]
```
julia> 0:1 isa AbstractUnitRange
true

julia> using StaticRanges

julia> srange(0, 1) isa AbstractUnitRange
false
```

Should the result at the end not be `true`, ideally?

**Comment by Tokazama** [comment]
It's mostly because static unit range support exists in Static.jl and this is usually for more complex ranges that people want to remain static

**Comment by nsajko** [comment]
Thank you, I didn't know that Static.jl and StaticNumbers.jl can be used for static ranges! Perhaps you should mention Static.jl/StaticNumbers.jl in this package's README, because the name "static ranges" (StaticRanges.jl) might get other people confused, too. I initially thought that this is the go-to Julia package for all things static range.
